### ISSUE TITLE
Vague `EACCES: permission denied` error

### ISSUE THREAD

**Issue by jedireza** [react-cosmos/react-cosmos#1061]
### What's wrong?

Sorry for opening a really general bug report, but I have no idea what the error could be here.

### Steps to reproduce

1.  Installed `yarn add react-cosmos`
2.  Created `cosmos.config.json` (contents below)
3.  Start it up `yarn cosmos`

### Screenshots

N/A

### User info

- Server terminal output
```
$ cosmos
[Cosmos] See you at http://localhost:5000
[Cosmos] Using webpack config found at webpack/config.js
[Cosmos] Serving static files from build
[Cosmos] Building webpack...
Starting type checking service...
Using 1 worker with 2048MB memory limit
(node:11329) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
✖ ｢wdm｣: Error: EACCES: permission denied, scandir '/.fseventsd'
    at Object.readdirSync (fs.js:779:3)
    at GlobSync._readdir (/Users/reza/projects/foo/node_modules/glob/sync.js:288:41)
    at GlobSync._readdirInGlobStar (/Users/reza/projects/foo/node_modules/glob/sync.js:267:20)
    at GlobSync._readdir (/Users/reza/projects/foo/node_modules/glob/sync.js:276:17)
    at GlobSync._processReaddir (/Users/reza/projects/foo/node_modules/glob/sync.js:137:22)
    at GlobSync._process (/Users/reza/projects/foo/node_modules/glob/sync.js:132:10)
    at GlobSync._processGlobStar (/Users/reza/projects/foo/node_modules/glob/sync.js:380:10)
    at GlobSync._process (/Users/reza/projects/foo/node_modules/glob/sync.js:130:10)
    at new GlobSync (/Users/reza/projects/foo/node_modules/glob/sync.js:48:10)
    at Function.globSync [as sync] (/Users/reza/projects/foo/node_modules/glob/sync.js:26:10)
```

- Browser console output
N/A

- Cosmos version
`5.0.0-beta.6`

- If bug occurred on upgrade: Working Cosmos version
N/A

- Cosmos config
```
{
    "webpack": {
        "watchDirs": ["src"],
        "configPath": "./webpack/config.js"
    }
}
```

- If applicable: webpack version
`4.39.3`

- If applicable: webpack config
N/A

### Additional context

I did just upgrade to MacOS Catalina. Could this be related to `System Integrity Protection`?

**Comment by jedireza** [comment]
Update: Just tried the same steps on macOS Mojave and got the same error.

**Comment by skidding** [comment]
Hi @jedireza,

Haven't seen this one before. But `watchDirs` should sit outside `webpack` in the config. Try this and see if the error continues. If it does, also try setting `watchDirs` to `[]`.

Let me know if you see any change. Thanks!

**Comment by jedireza** [comment]
🤦‍♂even after moving `watchDirs` up I get the same error. I'll continue to debug further as time permits.

**Comment by skidding** [comment]
Did you also try setting `watchDirs` to an empty list? This will show if the error is related to the watcher, which by the way isn’t required most of the time, even hot reloading works without it.

> If applicable: webpack config
> N/A

It actually seems like Cosmos is loading your webpack config from `webpack/config.js`.

In any case, a minimal reproducing repo would help determine if this issue is related to your setup or your machine.

**Comment by jedireza** [comment]
Turns out this was a symptom of our project using `CleanWebpackPlugin` with some egregious globs:

```diff
     plugins.push(
         new CleanWebpackPlugin({
             cleanOnceBeforeBuildPatterns: [
-                '**/*',
```

Many thanks to @joshua703 for finding this. 🙏
