### ISSUE TITLE
Error on first run: TypeError: Cannot read property 'invalid' of undefined

### ISSUE THREAD

**Issue by chovy** [react-cosmos/react-cosmos#1096]
Getting an error after installing

TypeError: Cannot read property 'invalid' of undefined

```
$ npm run cosmos

> edc-web@0.1.0 cosmos /home/ettinger/projects/profullstack/edcast/edc-web
> cosmos

[Cosmos] See you at http://localhost:5000
[Cosmos] Using webpack config found at webpack.config.js
[Cosmos] Server crashed...

  (╯°□°)╯︵ ┻━┻

TypeError: Cannot read property 'invalid' of undefined
    at _callee2$ (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:66:35)
    at tryCatch (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:22:103)
    at _next (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:24:194)
    at /home/ettinger/projects/profullstack/edcast/edc-web/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:24:364
    at new Promise (<anonymous>)
    at /home/ettinger/projects/profullstack/edcast/edc-web/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:24:97
    at _webpackDevServer (/home/ettinger/projects/profullstack/edcast/edc-web/node_modules/react-cosmos/dist/plugins/webpack/devServer.js:148:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edc-web@0.1.0 cosmos: `cosmos`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edc-web@0.1.0 cosmos script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ettinger/.npm/_logs/2019-12-10T21_03_36_033Z-debug.log
```

**Comment by skidding** [comment]
Hi @chovy,

What webpack version do you have installed?

**Comment by skidding** [comment]
Also, would you please share you webpack config

**Comment by chovy** [comment]
This was with webpack3. I downgraded to 4 and it worked.

**Comment by skidding** [comment]
Added a mention to webpack 4 in the README #1099.
