### ISSUE TITLE
clean-webpack-plugin breaks webpack build

### ISSUE THREAD

**Issue by arseneyr** [react-cosmos/react-cosmos#1244]
### What's wrong?

Using `clean-webpack-plugin` with no options causes errors during webpack compilation.

### Steps to reproduce

Run `cosmos` with the following `webpack.config.js`:
```js
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

module.exports = {
  entry: "./index.js",
  plugins: [new CleanWebpackPlugin()],
};
```

### User info

- Server terminal output (on Windows)
```
 ｢wdm｣: Error: EPERM: operation not permitted, scandir 'C:/$Recycle.Bin/S-1-5-18'
    at Object.readdirSync (fs.js:795:3)
    at GlobSync._readdir (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:288:41)
    at GlobSync._readdirInGlobStar (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:267:20)
    at GlobSync._readdir (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:276:17)
    at GlobSync._processReaddir (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:137:22)
    at GlobSync._process (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:132:10)
    at GlobSync._processGlobStar (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:380:10)
    at GlobSync._process (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:130:10)
    at GlobSync._processGlobStar (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:383:10)
    at GlobSync._process (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:130:10)
    at new GlobSync (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:48:10)
    at Function.globSync [as sync] (C:\Users\a\Repos\react-cosmos-issue\node_modules\glob\sync.js:26:10)
    at C:\Users\a\Repos\react-cosmos-issue\node_modules\globby\index.js:78:35
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (C:\Users\a\Repos\react-cosmos-issue\node_modules\globby\index.js:77:19)
    at module.exports.sync (C:\Users\a\Repos\react-cosmos-issue\node_modules\del\index.js:57:16)
```
- Cosmos version
5.4.0
- Cosmos config
None
- If applicable: webpack version
4.44.1
- If applicable: webpack config
See above

### Additional context

This seems to be caused by cosmos setting the webpack `output.path` to `'/'`. The default glob for `clean-webpack-plugin` is `**/*` which it combines with `output.path` and tries to stat all files on the machine. Is overwriting the `output.path` expected? Is `clean-webpack-plugin` just not supported and I should filter it out?

This is slightly related to issue #1061 but happens even without any options passed to `clean-webpack-plugin`.

**Comment by skidding** [comment]
> Is overwriting the output.path expected?

It is. Cosmos tries to reuse as much as possible from your webpack config (loaders, plugins, etc), but `entry` and `output` are two things it needs control over. In dev mode output.path needs to be `/` for [historical reasons](https://github.com/react-cosmos/react-cosmos/blob/0ab7dd688173c5b95963e82731eef607b992b236/packages/react-cosmos/src/plugins/webpack/webpackConfig/devServer.ts#L69-L71). And in export mode the output path is where the export will be generated (controlled via `exportPath` in the cosmos config).

> Is clean-webpack-plugin just not supported and I should filter it out?

Probably. It would be nice to prevent future issues for other people that use this plugin, but omitting it is probably the easiest fix. That said, is this plugin active in development? If feels weird, since in development the bundle is stored in memory, so webpack shouldn't touch your file system. So if you don't plan on using Cosmos exports, I'd say just disable this plugin in dev mode.

Let me know if there's anything else I can help with.

**Comment by arseneyr** [comment]
> That said, is this plugin active in development?

I'm using webpack for web extension development and the browser needs to have all the assets written to disk for the extension to load/reload. Not having `clean-webpack-plugin` enabled has led to some weird stale asset issues in the past but this seems to be a niche setup so I don't mind filtering it out. Thanks for the explanation.
