### ISSUE TITLE
"[404] Not Found (/dist/cosmos.userdeps.proxy.js) " with snowpack v3.1.2

### ISSUE THREAD

**Issue by OrcaXS** [react-cosmos/react-cosmos#1320]
### What's wrong?
I've just cloned https://github.com/react-cosmos/react-cosmos-snowpack and upgraded snowpack to latest (3.1.2). 
`yarn start` / `yarn cosmos` runs without error, but `localhost:5000` stuck at "Waiting for renderer...", then snowpack logs:
 ```
[17:33:41] [snowpack] File changed: src/cosmos.userdeps.js
[17:33:48] [snowpack] [404] Not Found (/dist/cosmos.userdeps.proxy.js) (x2)
```

It runs fine on snowpack v3.0.13.
### Steps to reproduce
1. Clone https://github.com/react-cosmos/react-cosmos-snowpack
2. Replace `"snowpack": "^3.0.0"` with `"snowpack": "^3.1.2"` in `package.json`
3. `yarn` && `yarn start`
4. `yarn cosmos`
5. open `localhost:5000` and page keeps showing "Waiting for renderer..."

### User info

- Server terminal output

<details>
  <summary>yarn start</summary>

  ```
yarn run v1.22.10
$ snowpack dev
[17:33:38] [snowpack] Server started in 12ms.
[17:33:38] [snowpack] Local: http://localhost:8080
[17:33:38] [snowpack] Network: http://192.168.10.167:8080
[17:33:41] [snowpack] File changed: src/cosmos.userdeps.js
[17:33:48] [snowpack] [404] Not Found (/dist/cosmos.userdeps.proxy.js) (x2)
```
</details>

<details>
  <summary>yarn cosmos</summary>

  ```
yarn run v1.22.10
$ /home/orcaxs/dev/react-cosmos-snowpack/node_modules/.bin/cosmos
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Serving static files from public
[Cosmos] See you at http://localhost:5000
[Cosmos] Generated src/cosmos.userdeps.js
```

</details>

- Browser console output
`index.cosmos.js:7 GET http://localhost:8080/dist/cosmos.userdeps.proxy.js net::ERR_ABORTED 404 (Not Found)`
- Cosmos version
Seems both `5.6.0-alpha.6` and `5.6.1` have the same issue
- Cosmos config
```json
{
  "staticPath": "public",
  "userDepsFilePath": "src/cosmos.userdeps.js",
  "experimentalRendererUrl": "http://localhost:8080/_renderer.html"
}
```

**Comment by skidding** [comment]
The weird part is that it requests `/dist/cosmos.userdeps.proxy.js`, when the actual file's path is `/dist/cosmos.userdeps.js`. Any ideea where `.proxy.js` comes from?

**Comment by OrcaXS** [comment]
From `/dist/index.cosmos.js`:

```js
import * as  __SNOWPACK_HMR__ from '../_snowpack/hmr-client.js';
import.meta.hot = __SNOWPACK_HMR__.createHotContext(import.meta.url);
import * as __SNOWPACK_ENV__ from '../_snowpack/env.js';
import.meta.env = __SNOWPACK_ENV__;

import {mountDomRenderer} from "../_snowpack/pkg/react-cosmos.dom.v5.6.0-alpha.6.js";
import {decorators, fixtures, rendererConfig} from "./cosmos.userdeps.proxy.js";
mountDomRenderer({rendererConfig, decorators, fixtures});
if (import.meta.hot) {
  import.meta.hot.accept();
}
```

**Comment by OrcaXS** [comment]
I tried changing 
`import { decorators, fixtures, rendererConfig } from './cosmos.userdeps';`
 to `import { decorators, fixtures, rendererConfig } from './cosmos.userdeps.js';`, the 404 error is gone. 

But then snowpack logs: 
```
Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] /home/orcaxs/dev/react-cosmos-snowpack/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
   Module "fs" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] /home/orcaxs/dev/react-cosmos-snowpack/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
   Module "url" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] /home/orcaxs/dev/react-cosmos-snowpack/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
   Module "child_process" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] /home/orcaxs/dev/react-cosmos-snowpack/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
   Module "http" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] /home/orcaxs/dev/react-cosmos-snowpack/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
   Module "https" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] fs?commonjs-external
   Module "fs" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] url?commonjs-external
   Module "url" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] child_process?commonjs-external
   Module "child_process" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] http?commonjs-external
   Module "http" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [esinstall:xmlhttprequest-ssl] https?commonjs-external
   Module "https" (Node.js built-in) is not available in the browser. Run Snowpack with --polyfill-node to fix.
[19:30:31] [snowpack] Error: Install failed.
    at Object.install (/home/orcaxs/dev/react-cosmos-snowpack/node_modules/snowpack/lib/index.js:44201:23)
    at async Object.installPackages (/home/orcaxs/dev/react-cosmos-snowpack/node_modules/snowpack/lib/index.js:54309:25)
    at async inProgressBuilds.add.priority (/home/orcaxs/dev/react-cosmos-snowpack/node_modules/snowpack/lib/index.js:54709:64)
    at async run (/home/orcaxs/dev/react-cosmos-snowpack/node_modules/snowpack/lib/index.js:46988:29)
[19:30:31] [snowpack] Error: Install failed.
[19:30:31] [snowpack] [500] /_snowpack/pkg/engine.io-client.v3.3.2.js
```

Then I tried adding `polyfillNode: true` to `snowpack.config.js`'s `packageOptions`, snowpack proceeds without error and cosmos page appears to be loading. But now `localhost:5000` shows some weird error:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/1764123/112296966-498d1100-8cd0-11eb-9a3d-73687459db74.png">

I don't think there're more than one react/dom copies existing in the project.

**Comment by skidding** [comment]
It seems odd that anything in that project would require Node.js APIs on the client. Did you try downgrading Snowpack a few patch versions to narrow down the release that broke this integration?

**Comment by OrcaXS** [comment]
I've tried 3.0.13, 3.1.0, 3.1.1 and 3.1.2, looks like 3.0.13 is the last working version. Haven't tried those `-pre` versions.

**Comment by nfour** [comment]
Can confirm same behavior.

**Comment by IgnusG** [comment]
Here are the full stack traces for the error:
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react-cosmos-shared2.FixtureLoader.v5.6.1.js:1560)
    at Object.useMemo (react-cosmos-shared2.FixtureLoader.v5.6.1.js:1615)
    at FixtureProvider (react-cosmos-shared2.FixtureLoader.v5.6.1.js:4165)
    at renderWithHooks (react-cosmos.dom.v5.6.2.js:18388)
    at mountIndeterminateComponent (react-cosmos.dom.v5.6.2.js:21214)
    at beginWork (react-cosmos.dom.v5.6.2.js:22452)
    at HTMLUnknownElement.callCallback (react-cosmos.dom.v5.6.2.js:7351)
    at Object.invokeGuardedCallbackDev (react-cosmos.dom.v5.6.2.js:7400)
    at invokeGuardedCallback (react-cosmos.dom.v5.6.2.js:7462)
    at beginWork$1 (react-cosmos.dom.v5.6.2.js:27356)
```

```
The above error occurred in the <FixtureProvider> component:

    at FixtureProvider (http://localhost:8080/_snowpack/pkg/react-cosmos-shared2.FixtureLoader.v5.6.1.js:4156:24)
    at FixtureLoader (http://localhost:8080/_snowpack/pkg/react-cosmos-shared2.FixtureLoader.v5.6.1.js:4253:5)
    at DomFixtureLoader (http://localhost:8080/_snowpack/pkg/react-cosmos.dom.v5.6.2.js:29976:23)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-cosmos.dom.v5.6.2.js:23488
```

I presume its the third point from the list, that there are multiple versions of React being used as a result of being compiled by snowpack. Snowpack changed it's behavior to now compile all dependencies along with the code which might be the root of this issue (I assume this is what also causes the above exceptions with node polyfills since snowpack compiles the whole cosmos library it seems and thus needs node features for cosmo's client etc. libraries).
https://github.com/snowpackjs/snowpack/pull/2878 
https://github.com/snowpackjs/snowpack/blob/main/snowpack/CHANGELOG.md#snowpack310-2021-03-19

**Comment by nderscore** [comment]
After adding `packageOptions.polyfillNode: true` to my snowpack config, I was able to get this working again by manually adding `react` as a `peerDependency` inside the `package.json`s of both the `react-cosmos` and `react-cosmos-shared2` packages.

**Comment by mzedeler** [comment]
I have this issue as well. Let me know if there is anything I can do to help get this fixed.

**Comment by skidding** [comment]
Snowpack has been deprecated since April 20, 2022. Closing this.
