### ISSUE TITLE
WebpackOptionsValidationError

### ISSUE THREAD

**Issue by suityou01** [react-cosmos/react-cosmos#1340]
### What's wrong?

[Cosmos] Server crashed...

  (╯°□°)╯︵ ┻━┻

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'infrastructureLogging'.

### Steps to reproduce

1 Install Cosmos into my react project, 
2 Add the 2 lines to the script stanza of my package.json 
3 Run npm run cosmos (step 3 of getting started guide)

### User info

- Server terminal output
```
[Cosmos] Server crashed...

  (╯°□°)╯︵ ┻━┻

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'infrastructureLogging'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           infrastructureLogging: ...
         }
       })
     ]
    at webpack (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\webpack\lib\webpack.js:19:9)
    at _callee2$ (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\react-cosmos\dist\plugins\webpack\devServer.js:79:31)
    at tryCatch (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\react-cosmos\dist\plugins\webpack\devServer.js:24:103)
    at _next (C:\Users\suity\Documents\rhodium\Wireframes\WebClient\rhodiumstorybook\node_modules\react-cosmos\dist\plugins\webpack\devServer.js:26:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  validationErrors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ]
}
```

**Comment by gleb-altarey** [comment]
Faced the same issue today

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/104499946/206513765-77850e18-46e1-4876-962b-f4274c7322dd.png">

My local changes 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/104499946/206513971-6c63ab78-2064-4d57-b1fe-82f68cf543c2.png">

**Comment by skidding** [comment]
Hi @gleb-altarey, what webpack version are you using?

Either `infrastructureLogging` has been deprecated or you're using an older webpack version that doesn't support it.

Either way you can remove it by defining a webpack config override [as defined here](https://github.com/react-cosmos/react-cosmos/blob/main/docs/README.md#webpack-config-override) and `delete webpackConfig. infrastructureLogging` in it. Let me know if you need a more concrete example.
