### ISSUE TITLE
Fixtures with FetchMock do not work with Create Rect App 5

### ISSUE THREAD

**Issue by gcwiak** [react-cosmos/react-cosmos#1395]
At first, big thanks for React Cosmos, I find it really helpful tool! 🥇 👍 

### What's wrong?

Fixtures with FetchMock stopped working (fetch-mock doesn't return the declared response anymore) after upgrading create-react-app from 4.0.3 to 5.0.1.

### Steps to reproduce

I have created sample application for reproducing this problem.

* On this branch, with CRA 4, **_it works correctly_**: 
https://github.com/gcwiak/cra-vs-react-cosmos/tree/cra_4-react_cosmos_fetch
1. Start React Cosmos with `npm run cosmos`
2. Open App fixture
3. Fixture is rendered correctly, showing the `FROM_Fixture` text provided by FetchMock:
![image](https://user-images.githubusercontent.com/9904686/190387088-cc984483-4047-4c2f-81b8-6b9145004b5c.png)

* On this branch, with CRA upgraded to 5, **_it fails to mock the fetch call_**
https://github.com/gcwiak/cra-vs-react-cosmos/tree/cra_5-react_cosmos_fetch

1.  Start React Cosmos with `npm run cosmos`
2.  Open `App` fixture
3.  Nothing is rendered, console shows the following errors
```
Uncaught TypeError: Cannot read properties of undefined (reading 'decode')
    at new URLStateMachine (url-state-machine.js:547:1)
    at module.exports.basicURLParse (url-state-machine.js:1260:1)
    at new URLImpl (URL-impl.js:13:1)
    at Object.setup (URL.js:376:1)
    at new URL (URL.js:31:1)
    at normalizeUrl (request-utils.js:70:1)
    at Object.normalizeRequest (request-utils.js:96:1)
    at FetchMock.fetchHandler (fetch-handler.js:119:1)
    at DataFetchingComponent.tsx:8:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
URLStateMachine @ url-state-machine.js:547
module.exports.basicURLParse @ url-state-machine.js:1260
URLImpl @ URL-impl.js:13
setup @ URL.js:376
URL @ URL.js:31
normalizeUrl @ request-utils.js:70
normalizeRequest @ request-utils.js:96
FetchMock.fetchHandler @ fetch-handler.js:119
(anonymous) @ DataFetchingComponent.tsx:8
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
index.js:1 The above error occurred in the <DataFetchingComponent> component:

    at DataFetchingComponent (http://localhost:4000/main.js:197:76)
    at p
    at header
    at div
    at App
    at FetchMock (http://localhost:4000/main.js:506:34)
    at __WEBPACK_DEFAULT_EXPORT__
    at FixtureElement (http://localhost:4000/main.js:56809:24)
    at FixtureCapture (http://localhost:4000/main.js:55239:23)
    at ErrorCatch (http://localhost:4000/main.js:59771:5)
    at FixtureProvider (http://localhost:4000/main.js:56607:24)
    at FixtureLoader (http://localhost:4000/main.js:56233:5)
    at DomFixtureLoader (http://localhost:4000/main.js:59586:23)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorCatch.
```

### User info

- Server terminal output
```
$ npm run cosmos

> cra-vs-react-cosmos@0.1.0 cosmos
> cosmos

[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Serving static files from public
[Cosmos] See you at http://localhost:4000
[Cosmos] Using webpack config found at node_modules/react-scripts/config/webpack.config.js
[Cosmos] Building webpack...
webpack built 4178d5585cd9efc6250f in 4372ms
WARNING in ./node_modules/@base2/pretty-print-object/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/grzegorz/workspace/cra-vs-react-cosmos/node_modules/@base2/pretty-print-object/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/grzegorz/workspace/cra-vs-react-cosmos/node_modules/@base2/pretty-print-object/src/index.ts'

WARNING in DefinePlugin
Conflicting values for 'process.env'

WARNING in [eslint] 
src/App.fixture.tsx
  Line 6:1:  Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 4 warnings
No issues found.
```

- Cosmos version: `5.7.2`
- `react-mock/fetch` version: `0.3.0`
- Cosmos config
```
{
  "port": 4000,
  "staticPath": "public",
  "watchDirs": ["src"],
  "webpack": {
    "configPath": "react-scripts/config/webpack.config"
  }
}
```

**Comment by skidding** [comment]
Thanks for posting this and @msrokaxw for this solution.

Closing this because it's related to http://github.com/skidding/react-mock/ which unfortunately is no longer maintained.
