### ISSUE TITLE
When using vite, it's not possible to use an alternative entrypoint to `src/main.tsx`

### ISSUE THREAD

**Issue by seveibar** [react-cosmos/react-cosmos#1663]
In vite, you can specify an alternative to `src/main.tsx` in your `index.html` file

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@tscircuit/schematic-viewer</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/someotherpath/main.tsx"></script>
  </body>
</html>
```

For some reason, this causes fixtures to never load, the renderer will hang forever.

![image](https://github.com/user-attachments/assets/169a53b2-7592-4581-a441-77cd55a51e7d)

With `src/main.tsx`...

```
$ cosmos
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Found 1 plugin: Vite
[Cosmos] Port 5000 already in use, trying next...
[Cosmos] See you at http://localhost:5001
[Cosmos] Using vite config found at vite.config.js
[Cosmos] Replacing vite index module at src/main.tsx
```

With `vite/main.tsx`...

```
$ cosmos
[Cosmos] Using cosmos config found at cosmos.config.json
[Cosmos] Found 1 plugin: Vite
[Cosmos] Port 5000 already in use, trying next...
[Cosmos] See you at http://localhost:5001
[Cosmos] Using vite config found at vite.config.js
```

Note that the last line is missing, indicating the index module is not being replaced.

**Comment by ovidiuch** [comment]
@seveibar Have you tried setting `vite.indexPath` in the Cosmos config?

https://reactcosmos.org/docs/getting-started/vite#configuration

**Comment by seveibar** [comment]
I get this error when changing the `indexPath`

![image](https://github.com/user-attachments/assets/50523717-886a-42e5-8729-60f69c4259f3)

```
[Cosmos] Using vite config found at vite.config.ts
Error: Package subpath './main.tsx' is not defined by "exports" in /Users/seve/w/tsc/runframe/node_modules/vite/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:299:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:646:9)
    at resolveExports (node:internal/modules/cjs/loader:621:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:711:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1198:27)
    at Function.resolve (node:internal/modules/helpers:133:19)
    at resolveFrom (file:///Users/seve/w/tsc/runframe/node_modules/react-cosmos/dist/utils/resolve.js:11:20)
    at resolveFromSilent (file:///Users/seve/w/tsc/runframe/node_modules/react-cosmos/dist/utils/resolveSilent.js:15:16)
    at resolveLoose (file:///Users/seve/w/tsc/runframe/node_modules/react-cosmos/dist/utils/resolveLoose.js:7:11)
    at createCosmosViteConfig (file:///Users/seve/w/tsc/runframe/node_modules/react-cosmos-plugin-vite/dist/createCosmosViteConfig.js:11:15) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by ovidiuch** [comment]
Interesting, haven't seen that error before but a few thoughts:

- If your repo is public then send me a link because it's easier for me to debug if I can peak under the hood. A minimal reproducing repo is also good.
- Maybe `./main.tsx` would be a better value for `vite.indexPath` given that the Cosmos config is already in the `vite` folder.
- Does it work regardless of the error, though? Based on the related code path, [Cosmos tries to resolve a module path and if it fails it just does a `path.join`](https://github.com/react-cosmos/react-cosmos/blob/8026efa62623e9ecbdb299dc906bc79bd01f101a/packages/react-cosmos/src/utils/resolveLoose.ts) which should also work OK for the vite index path. If this is the case then maybe we should just omit reporting `ERR_PACKAGE_PATH_NOT_EXPORTED` errors inside [resolveSilent](https://github.com/react-cosmos/react-cosmos/blob/8026efa62623e9ecbdb299dc906bc79bd01f101a/packages/react-cosmos-plugin-webpack/src/server/utils/resolveSilent.ts#L8).

**Comment by seveibar** [comment]
@ovidiuch here's a reproduction, the main branch works so this represents "breaking changes" and I think it's pretty minimal: https://github.com/tscircuit/runframe/pull/2

The reason we do this is because we use `lib` for all our libraries instead of `src` as a convention, and having both `lib` and `src` is confusing to contributors

**Comment by ovidiuch** [comment]
@seveibar `tscircuit/runframe` does seem to be a public repo so I don't have access to it.

**Comment by seveibar** [comment]
@ovidiuch 🤦 sorry, opened it up!

**Comment by ovidiuch** [comment]
@seveibar So as predicated in the 3rd bullet point from my previous message, everything seems to work just fine already.

![localhost_5001__fixtureId=%7B%22path%22%3A%22examples%2Fresistor fixture tsx%22%7D](https://github.com/user-attachments/assets/87b45721-b05c-432c-9a29-c6b384dc5d81)

Cosmos has an internal helper that will employ various strategies when resolving a user path. If the path is module-like, it will try to import it. In your case `vite/main.tsx` could be a `main.tsx` entrypoint from the `vite` package that is indeed installed in your project. It tries that, fails (hence the error you're seeing) and then goes with the fallback, which is to resolve the path relative to your root dir (the parent dir of your cosmos config unless configured otherwise).

So it already works, but if you want to get rid of the error you just need to make this change:

<img width="582" alt="image" src="https://github.com/user-attachments/assets/cd686569-1cb4-41cb-846e-667bf55ed995">

We should also supress this error in case other users bump into it. If you're interested in a small contribution all you need to do is add another condition like `!['MODULE_NOT_FOUND', 'ERR_PACKAGE_PATH_NOT_EXPORTED'].includes(err.code)` here: https://github.com/react-cosmos/react-cosmos/blob/8026efa62623e9ecbdb299dc906bc79bd01f101a/packages/react-cosmos-plugin-webpack/src/server/utils/resolveSilent.ts#L8.

**Comment by seveibar** [comment]
yes this is a huge mistake on my end i guess- I just re-pulled the branch and it is now working (no longer stuck on the loader!)- I've had some issues with bun and vite in the past, so maybe i was seeing that before. Thanks for working with me on this!! I will try to make that contribution as well!! 🙏

**Comment by seveibar** [comment]
Ok i thought i was going crazy when this happened AGAIN. I removed my node_modules, reinstalled and re-ran and it worked! There is some kind of (vite?) caching issue

**Comment by andreiwow2** [comment]
I also seem to have a similar issue, after following through with the suggestions from this thread, I noticed that I was missing `./` in my indexPath, but that still did not solve the issue for me, indeed, now I can also see the line `[Cosmos] Replacing vite index module at src/index.tsx`, and I can see the requests in the Browser as it loads the fixtures and their props, but still that loading won't go away and I can't see my Components.

**Comment by usernein** [comment]
i was having the same issue because i had an alternative index path as well. setting vite.indexPath starting with "./" solved it! thanks!

**Comment by ovidiuch** [comment]
Just pushed a `canary` version that addresses these set of issues, please try it out. More details here: https://github.com/react-cosmos/react-cosmos/pull/1704#issuecomment-2815511517

**Comment by ovidiuch** [comment]
Closing this Vite onboarding has been revamped to avoid these issues in React Cosmos 7 beta.

Install using `react-cosmos@next` and `react-cosmos-plugin-vite@next`.

See migration guide: https://reactcosmos.org/docs/migration-guide.
