### ISSUE TITLE
Cannot find module 'enzyme' from 'enzyme.js'

### ISSUE THREAD

**Issue by kfern** [react-cosmos/react-cosmos#567]
### What's up?

I'm trying to reproduce the example at https://github.com/react-cosmos/react-cosmos#using-enzyme

When I use 

`import createTestContext from 'react-cosmos-test/enzyme';`

I get 

```
 FAIL  src\components\Welcome.test.js
  ? Test suite failed to run
    Cannot find module 'enzyme' from 'enzyme.js'
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/react-cosmos-test/lib/enzyme.js:13:15)
```
Environment:

```
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "cosmos": "cosmos",
    "cosmos:export": "cosmos-export"
  },
  "devDependencies": {
    "react-cosmos": "^3.2.0",
    "react-cosmos-test": "^3.2.0"
  }

```
Is it a bug or am I doing something wrong?

Thanks in advance

**Comment by kfern** [comment]
Beginner failure: Enzyme was not installed

I have installed it with:

npm i --save-dev enzyme enzyme-adapter-react-16

Now I get:

```
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })` before using any of Enzyme's top level APIs, where `Adapter` is the adapter corresponding to the library currently being tested. For example:

import Adapter from 'enzyme-adapter-react-15';

To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html

```
What should be the minimum configuration? 
Is something missing in the example?

**Comment by razagill** [comment]
You need to setup the adapter for `enzyme` before you run any tests. Put the following in your `setupTests.js` file.
```
const enzyme = require("enzyme");
const Adapter = require("enzyme-adapter-react-16");

enzyme.configure({ adapter: new Adapter() });
```

**Comment by kfern** [comment]
@razagill Works. Thank you!!

**Comment by skidding** [comment]
Awesome. 

We need to do a better job at signaling missing "peer" dependencies in the future.
