### ISSUE TITLE
Error importing createTestContext

### ISSUE THREAD

**Issue by adamszeptycki** [react-cosmos/react-cosmos#612]
### What's up?

I'm getting an error while running tests.

```
ERROR in ./node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in '/Users/justme/Developer/MyProject/frontend/node_modules/resolve-from'
 @ ./node_modules/resolve-from/index.js 3:15-32
 @ ./node_modules/react-cosmos-shared/lib/server/resolve-user-path.js
 @ ./node_modules/react-cosmos-shared/lib/server/index.js
 @ ./node_modules/react-cosmos-test/lib/generic.js
 @ ./node_modules/react-cosmos-test/lib/enzyme.js
 @ ./node_modules/react-cosmos-test/enzyme.js
 @ ./src/components/pixel/login/tests/login-test.jsx
 @ ./src -test\.jsx?$
 @ ./webpack.karma.context.js
```
I have my small project where I try to add cosmos. I was able to render comonent in cosmos but I can't run tests with your API.

### Mkay, tell me more...

I did track down an error to this line:
```
import createTestContext from 'react-cosmos-test/enzyme'
```

**Comment by skidding** [comment]
Hi @adamszeptycki,

Is your project public, or can you provide a *minimum reproducing repo* that I can debug? Thanks!

PS. I like your OS username ;)

**Comment by adamszeptycki** [comment]
Thanks :)

Here is a project I forked and just added the cosmos.
https://github.com/adamszeptycki/react-example

**Comment by adamszeptycki** [comment]
To be fair I have a different error... :|

**Comment by adamszeptycki** [comment]
Ok, the error I'm getting is probably connected with the fact that I'm using karma.
```
  {
    "message": "Uncaught Error: Cannot find module \".\"\nat webpack:///node_modules/use/utils.js:3:0 <- webpack.karma.context.js:251355:151\n\nError: Cannot find module \".\"\n    at webpackMissingModule (webpack:///node_modules/use/utils.js:3:0 <- webpack.karma.context.js:251355:83)\n    at Object.<anonymous> (webpack:///node_modules/use/utils.js:3:0 <- webpack.karma.context.js:251355:161)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)\n    at Object.<anonymous> (webpack:///node_modules/use/index.js:10:0 <- webpack.karma.context.js:93696:13)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)\n    at Object.<anonymous> (webpack:///node_modules/snapdragon/lib/compiler.js:3:0 <- webpack.karma.context.js:251170:11)\n    at Object.<anonymous> (webpack.karma.context.js:251346:30)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)\n    at Object.<anonymous> (webpack:///node_modules/snapdragon/index.js:5:0 <- webpack.karma.context.js:249183:16)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)",
    "str": "Uncaught Error: Cannot find module \".\"\nat webpack:///node_modules/use/utils.js:3:0 <- webpack.karma.context.js:251355:151\n\nError: Cannot find module \".\"\n    at webpackMissingModule (webpack:///node_modules/use/utils.js:3:0 <- webpack.karma.context.js:251355:83)\n    at Object.<anonymous> (webpack:///node_modules/use/utils.js:3:0 <- webpack.karma.context.js:251355:161)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)\n    at Object.<anonymous> (webpack:///node_modules/use/index.js:10:0 <- webpack.karma.context.js:93696:13)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)\n    at Object.<anonymous> (webpack:///node_modules/snapdragon/lib/compiler.js:3:0 <- webpack.karma.context.js:251170:11)\n    at Object.<anonymous> (webpack.karma.context.js:251346:30)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)\n    at Object.<anonymous> (webpack:///node_modules/snapdragon/index.js:5:0 <- webpack.karma.context.js:249183:16)\n    at __webpack_require__ (webpack:///webpack/bootstrap%20eb73f15159f847148784:19:0 <- webpack.karma.context.js:20:30)"
  }

```
Any ideas?

**Comment by adamszeptycki** [comment]
We migrated from karma to jest and it works now.
