### ISSUE TITLE
Experimental addJestWrapper kills mobx 4 functions in react-cosmos-test

### ISSUE THREAD

**Issue by SimeonC** [react-cosmos/react-cosmos#658]
So it looks like the `addJestWrapper` function with it's happy "HIGHLY EXPERIMENTAL" comment is quite happily incorrectly trying to break mobx observable values.

So my fixture goes something like this:
```jsx
import { observable } from 'mobx';
class TestStore {
  @observable.shallow pluralization = [];
}
const testLocale = new TestStore();
testLocale.pluralization = ['one', 'other'];
export default {
  name: 'basic render',
  component: Select,
  props: {
    selected: testLocale
  }
};
```

Trying to run my tests like this:
```jsx
import createTestContext from 'react-cosmos-test/enzyme';
import fixture from './__fixtures__/basic';

const { mount, getWrapper, getRootWrapper, setProps } = createTestContext({
  fixture
});
```

Gives me this big error:
```sh
  ● Test suite failed to run

    [mobx] The shallow modifier / decorator can only used in combination with arrays, objects and maps

      2 | import fixture from './__fixtures__/basic';
      3 | 
    > 4 | const { mount, getWrapper, getRootWrapper, setProps } = createTestContext({
      5 |   fixture
      6 | });
      7 | 
      
      at invariant (node_modules/mobx/lib/mobx.js:2654:15)
      at fail$1 (node_modules/mobx/lib/mobx.js:2649:5)
      at ObservableValue.shallowEnhancer [as enhancer] (node_modules/mobx/lib/mobx.js:1570:12)
      at ObservableValue.Object.<anonymous>.ObservableValue.prepareNewValue (node_modules/mobx/lib/mobx.js:959:25)
      at ObservableObjectAdministration.Object.<anonymous>.ObservableObjectAdministration.write (node_modules/mobx/lib/mobx.js:1043:31)
      at TestStore.set [as pluralization] (node_modules/mobx/lib/mobx.js:1207:28)
      at Object.update (node_modules/traverse/index.js:134:50)
      at walker (node_modules/traverse/index.js:191:54)
      at node_modules/traverse/index.js:208:29
      at Array.forEach (native)
      at forEach (node_modules/traverse/index.js:298:31)
      at walker (node_modules/traverse/index.js:203:13)
      at node_modules/traverse/index.js:208:29
      at Array.forEach (native)
      at forEach (node_modules/traverse/index.js:298:31)
      at walker (node_modules/traverse/index.js:203:13)
      at walk (node_modules/traverse/index.js:226:7)
      at Traverse.Object.<anonymous>.Traverse.map (node_modules/traverse/index.js:46:12)
      at Function.traverse.(anonymous function) [as map] (node_modules/traverse/index.js:308:23)
      at decorateFixture (node_modules/react-cosmos-test/lib/generic.js:55:31)
      at createContext (node_modules/react-cosmos-test/lib/generic.js:32:26)
      at createContext (node_modules/react-cosmos-test/lib/enzyme.js:31:44)
      at Object.<anonymous> (src/modules/FilteredLocalesSelect/index.test.jsx:4:22)
```

From my Tweaking the fix for this should just be the removal of happy highly experimental code which is the decorateFixture part of the code.
https://github.com/react-cosmos/react-cosmos/blob/f893982b785d5ddab37e9bdc5d3b3168c690bc82/packages/react-cosmos-test/src/generic.js#L43-L47

**Comment by skidding** [comment]
Sorry for the headache @SimeonC! 😇

If you can tell, does the error occur inside addJestWrapper or when the decorated prop is called?

**Comment by SimeonC** [comment]
Inside addJestWrapper I think. It looks like the test to wrap the function is picking up observables and trying to replace them with functions (they use get and set internally).

I think it could work if you ignore ES6 class getters, setters and inits. Although I haven’t tested what happens with the non class version mobx supports to see if that breaks as well/in a different way.

**Comment by SimeonC** [comment]
I used replicated this test in react-cosmos-test to play with it (need `mobx` in devDependencies), and tried several different ways of working around this with no success. Also I did some testing and it seems like it doesn't even try to wrap functions defined on the class which kinda makes it a bit worthless to recurse into them. It's also near impossible to detect this class compared to an object.

```jsx
it('should not apply jest.fn to getters/setters', () => {
  const { decorate, observable } = require('mobx');
  class TestClass {
    value = [];
    action = (value) => {
      this.value = value;
    }
  }
  decorate(TestClass, {
    value: observable.shallow
  });
  createContext({ renderer, fixture: { props: { key: new TestClass() } }, cosmosConfigPath: '/foo/path' });

  expect(getCosmosConfig).toHaveBeenCalledWith('/foo/path');
});
```

I'm fixing this locally by just removing the decorateFixture part (it's a little too automagic for my preferences anyway). Maybe the best solution would be to give an option to turn this on and off depending on your use case.
My Fix:
```js
export function createContext(args: TestContextArgs): ContextFunctions {
  const { fixture, proxies = detectUserProxies(args.cosmosConfigPath) } = args;

  return createLoaderContext({
    ...args,
    proxies,
    fixture
  });
}
```

**Comment by skidding** [comment]
Ideally we find the way to improve the "magic". But I admit it's a risky
road and don't want to grow frustration in the meantime.

I agree with you and I welcome an option like `autoMockProps` for the
createTestContext method. It should default to true for now, to not affect
other users unwillingly.

I'm deep into another Cosmos-related task at the moment so I can put much
time into this now. If you're interested in contributing I'll do my best to
help with review, merge, etc. And we can change the silly comment too :).

Thanks for all your support!

**Comment by SimeonC** [comment]
I did that PR, seeing as it took me all that time to find the problem.

**Comment by SimeonC** [comment]
To add more fuel to the fire, I found that the jest auto-mocker breaks ES6 Map (and I assume Set) as well!
Like a simple fixture of:
```
{
  props: {
    map: new Map()
  }
}
```
If you try do `this.props.map.keys()` in your component you get `Error: Uncaught [TypeError: Method Map.prototype.keys called on incompatible receiver #<Map>]`.
