### ISSUE TITLE
react-cosmos-playground build failed

### ISSUE THREAD

**Issue by mpachin** [react-cosmos/react-cosmos#688]
### What's up?

`yarn build` fails on building `react-cosmos-playground`

Environment:
windows 10
node 8.10.0
npm 5.6.0
yarn 1.6.0
current master branch of react-cosmos

```
> yarn build
yarn run v1.6.0
$ babel-node ./scripts/build.js
Building packages...
 DONE  react-cosmos-context-proxy
 DONE  react-cosmos-apollo-proxy
 DONE  react-cosmos-config
 DONE  react-cosmos-normalize-props-proxy
 DONE  react-cosmos-fetch-proxy
 DONE  react-cosmos-localstorage-proxy
 DONE  react-cosmos-redux-proxy
 DONE  react-cosmos-shared
 DONE  react-cosmos-test
 DONE  react-cosmos-xhr-proxy
 DONE  react-cosmos
 DONE  react-cosmos-loader
 DONE  react-cosmos-voyager2
 DONE  react-cosmos-router-proxy
 DONE  react-cosmos-state-proxy
 DONE  react-cosmos-voyager
 DONE  react-cosmos-telescope
 DONE  react-cosmos-scripts
 DONE  react-querystring-router
Building browser packages...
 ERROR  react-cosmos-playground
(node:12504) UnhandledPromiseRejectionWarning: ChildProcessError: `webpack --config packages/react-cosmos-playground/webpack.config.js --silent` failed with code 2
    at ChildProcess.<anonymous> (C:\Users\misha\Desktop\projects\github_forks\react-cosmos\node_modules\child-process-promise\lib\index.js:132:23)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\misha\Desktop\projects\github_forks\react-cosmos\node_modules\child-process-promise\node_modules\cross-spawn\lib\enoent.js:40:29)    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:12504) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12504) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 19.78s.
PS C:\Users\misha\Desktop\projects\github_forks\react-cosmos> node -v
v8.10.0
PS C:\Users\misha\Desktop\projects\github_forks\react-cosmos> npm -v
5.6.0
PS C:\Users\misha\Desktop\projects\github_forks\react-cosmos> yarn -v
1.6.0
PS C:\Users\misha\Desktop\projects\github_forks\react-cosmos>
```

### Mkay, tell me more...

[As written in documentation](https://github.com/react-cosmos/react-cosmos/blob/master/CONTRIBUTING.md#get-familiar-with-codebase) before starting implementing any feature we should first build project . Since `react-cosmos-playground` build fails, `yarn run lint` stops work either:
```
PS C:\Users\misha\Desktop\projects\github_forks\react-cosmos> yarn run lint
yarn run v1.6.0
$ xo --quiet

  examples\browserify\playground.js:3:33
  ✖  3:33  Unable to resolve path to module react-cosmos-playground.  import/no-unresolved

  1 error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\misha\Desktop\projects\github_forks\react-cosmos>
```
Also maybe it needs to be mentioned that `yarn test:watch` logs out
```
Test Suites: 28 failed, 1 skipped, 122 passed, 150 of 151 total
Tests:       50 failed, 4 skipped, 708 passed, 762 total
Snapshots:   8 passed, 8 total
Time:        125.194s
Ran all test suites.
```
I'm not sure if this is correct numbers.

**Comment by skidding** [comment]
Can you run `yarn webpack --config packages/react-cosmos-playground/webpack.config.js` independently to see if you get better logs?

Building the playground works on my macOS machine.

**Comment by mpachin** [comment]
Sure, here are logs:
```
PS C:\Users\misha\Desktop\test_clone_react-cosmos\react-cosmos> yarn webpack --config packages/react-cosmos-playground/webpack.config.js
yarn run v1.6.0
$ C:\Users\misha\Desktop\test_clone_react-cosmos\react-cosmos\node_modules\.bin\webpack --config packages/react-cosmos-playground/webpack.config.js
Hash: e0bfc9ef7a4331c9dc0a
Version: webpack 4.2.0
Time: 3326ms
Built at: 2018-5-23 10:04:10
       Asset       Size  Chunks             Chunk Names
    index.js    2.1 MiB    main  [emitted]  main
index.js.map   2.31 MiB    main  [emitted]  main
  index.html  182 bytes          [emitted]
Entrypoint main = index.js index.js.map
[./node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./node_modules/less-loader/dist/cjs.js!./packages/react-cosmos-playground/src/utils/global.less] ./node_modules/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./node_modules/less-loader/dist/cjs.js!./packages/react-cosmos-playground/src/utils/global.less 406 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {main} [built]
[./packages/react-cosmos-playground/src/index.js] 1.32 KiB {main} [built]
[./packages/react-cosmos-playground/src/static/FiraCode-Light.woff] 128 KiB {main} [built]
[./packages/react-cosmos-playground/src/static/cosmos.png] 36.9 KiB {main} [built]
[./packages/react-cosmos-playground/src/static/stars.png] 48.9 KiB {main} [built]
[./packages/react-cosmos-playground/src/utils/global.less] 1.45 KiB {main} [built]
[./packages/react-cosmos-playground/src/utils/page-title.js] 420 bytes {main} [built]
[./packages/react-querystring-router/index.js] 262 bytes {main} [built]
[./packages/react-querystring-router/src/router.js] 414 bytes {main} [built] [failed] [1 error]
[./packages/react-querystring-router/src/uri.js] 1.33 KiB {main} [built]
   [0] multi whatwg-fetch ./packages/react-cosmos-playground/src 40 bytes {main} [built]
    + 208 hidden modules

ERROR in ./packages/react-querystring-router/src/router.js
Module parse failed: Unexpected token (69:6)
You may need an appropriate loader to handle this file type.
|     const ComponentClass = getComponentClass(params);
|     const props = {
|       ...getComponentProps(params),
|       // Always send the components a reference to the router. This makes it
|       // possible for a component to change the page through the router and
 @ ./packages/react-querystring-router/index.js 8:17-40
 @ ./packages/react-cosmos-playground/src/index.js
 @ multi whatwg-fetch ./packages/react-cosmos-playground/src
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint html-webpack-plugin for "index.html" = index.html
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {html-webpack-plugin for "index.html"} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {html-webpack-plugin for "index.html"} [built]
        + 2 hidden modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mpachin** [comment]
I've just tested building project in VM / Ubuntu 18.04 LTS
Everything is fine including tests, react-cosmos-playground build went ok
It seems that described issue relates only to windows machines
Also I checked build on another windows laptop (third in row), the problem repeats

**Comment by skidding** [comment]
It seems like `./packages/react-querystring-router/src/router.js` is not being compiled by Babel, and maybe your Node version on the Window machine doesn't support spread operator.

This is odd, because the Playground's webpack config [is configured to compile the router source](https://github.com/react-cosmos/react-cosmos/blob/da9c355a2edca480603873b3ecef23bdabfa7623/packages/react-cosmos-playground/webpack.config.js#L43) as well. Maybe there's something wrong with that config that I'm missing.

**Comment by mpachin** [comment]
I'll try investigate further on that after [this issue](https://github.com/react-cosmos/react-cosmos/issues/687), if by then someone else does not fix this
For now I can work with VM

**Comment by mentaman** [comment]
I'm having the same issue.
![image](https://user-images.githubusercontent.com/2057934/40552797-79ffb452-6049-11e8-97c5-844b8f08ba2b.png)
Windows 10 too, 64bit.
My node and yarn are a bit newer than his.

**Comment by mentaman** [comment]
Ok I found a fix!

> {
>         test: /\.(jsx|js)$/,
>         include: [
>           src,
>           // Allow building playground from uncompiled monorepo deps
>           /react-cosmos-.+\/src\//,
>           /react-querystring-router/,
>           /react-cosmos-flow/
>         ],
>         use: 'babel-loader'
>       },

Use this:
![image](https://user-images.githubusercontent.com/2057934/40553497-7f7b2982-604b-11e8-95d0-82c5abc242bb.png)

Instead of this:
![image](https://user-images.githubusercontent.com/2057934/40553512-905a0912-604b-11e8-9bfa-ec95e7a22be9.png)

Just changed the react-cosmos-playground/webpack.config,js first rule.
and it builds succesfuly. I'm not sure why does it happen only on windows, and what exactly did I do.. But it works!

![image](https://user-images.githubusercontent.com/2057934/40554072-40602638-604d-11e8-87fc-d04b45652204.png)

**Comment by mentaman** [comment]
Later I had another windows issue it seems.. and fixed it too.

I tried to run the 

cd examples/context
yarn start

like the 
https://github.com/react-cosmos/react-cosmos/blob/master/CONTRIBUTING.md
suggested..

But had errors..
![image](https://user-images.githubusercontent.com/2057934/40554363-25da9522-604e-11e8-983b-3e6268252ae8.png)

It took the linux one instaed of the cmd.
So I changed the package.json to use the .cmd, and removed the linux one.
"start": "babel-node node_modules/.bin/cosmos.cmd"
![image](https://user-images.githubusercontent.com/2057934/40554444-6500ed96-604e-11e8-87e3-9792a02367a3.png)
But this cmd didn't work too..

So I just changed it to:

    "start": "babel-node ../../packages/react-cosmos/bin/cosmos.js"

which seems this is what the cmd has tried to. and it fixed it :)

**Comment by skidding** [comment]
@mentaman Thank for all your notes! I installed a Windows VM and confirm all you reported.

Would you be interested in addressing both issues in one PR? I can test everything on unix (Mac).

## 1. Playground build

This is the fix that I propose. It still targets the `src` dir only but accepts both types of slashes.

```diff
         include: [
           src,
           // Allow building playground from uncompiled monorepo deps
-          /react-cosmos-.+\/src\//,
-          /react-querystring-router\/src\//,
+          // Note: Support both forward and back slashes in file paths for
+          // cross OS compatibility
+          /(react-cosmos-.+|react-querystring-router)(\/|\\)src/,
           /react-cosmos-flow/
         ],
         use: 'babel-loader'
```

## 2. Start scripts

My takeaway is that npm binaries (`node_modules/.bin/*`) are platform specific, and we can't call `babel-node node_module/.bin/foo` reliably. Even thought it works on unix systems.

So I am on board with your `"start": "babel-node ../../packages/react-cosmos/bin/cosmos.js"` proposal, as long as we update all examples and the start script in the root package.json.

**Comment by skidding** [comment]
@mpachin This issue has been fixed. Can you please test latest master on your machine as well?

**Comment by mpachin** [comment]
@skidding Just tested on my win10x64 machine, build works :heart:
