### ISSUE TITLE
Mocking apollo InMemoryCache not working

### ISSUE THREAD

**Issue by jeznag** [react-cosmos/react-cosmos#757]
### What's wrong?
I'm trying to use the apollo proxy for a unit test.
I'm getting the below error triggered when my code tries to read from the Apollo InMemoryCache

```
console.error node_modules/apollo-utilities/lib/bundle.umd.js:790
    Error: Can't find field availableOptions on object (ROOT_QUERY) undefined.
        at readStoreResolver (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/apollo-cache-inmemory/src/readFromStore.ts:116:13)
        at executeField (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/graphql-anywhere/src/graphql.ts:192:18)
        at /Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/graphql-anywhere/src/graphql.ts:130:27
        at Array.forEach (native)
        at executeSelectionSet (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/graphql-anywhere/src/graphql.ts:123:27)
        at graphql (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/graphql-anywhere/src/graphql.ts:107:10)
        at diffQueryAgainstStore (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/apollo-cache-inmemory/src/readFromStore.ts:198:18)
        at readQueryFromStore (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/apollo-cache-inmemory/src/readFromStore.ts:56:10)
        at InMemoryCache.Object.<anonymous>.InMemoryCache.read (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/apollo-cache-inmemory/src/inMemoryCache.ts:94:12)
        at InMemoryCache.Object.<anonymous>.InMemoryCache.readQuery (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/apollo-cache-inmemory/src/inMemoryCache.ts:225:17)
        at updateCache (/Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/src/RequestData/SubmitForm.tsx:20:11)
        at /Users/jeremynagel/dev/energylink-project/react-components/data-exporter2/node_modules/src/data/store.ts:180:39
```

Here is the updateCache method (that gets called when the mutation is triggered). The error occurs at `cache.readQuery` (there is no problem when I run the app).
```
const updateCache = (cache: any) => {
  const { availableOptions } = cache.readQuery({ query: getAvailableOptions });

  cache.writeQuery({
    query: getAvailableOptions,
    data: {
      availableOptions: {
        ...availableOptions,
        submitted: true
      }
    }
  });
};
```

```
<Mutation mutation={saveExportDataRequest} update={updateCache}>
....
</Mutation>
```

### Steps to reproduce

This is my fixture:
```
export default {
  component: SubmitForm,
  context: {
    i18n: i18nInstance
  },
  apollo: {
    resolveWith: (apolloData: any) => {
      const fakeData = {
        availableOptions: {
         //left out for conciseness
        }
      };
      apolloData.cache.writeQuery({
        query: getAvailableOptions,
        data: fakeData
      });

      return {
        availableOptions: fakeData,
        saveExportDataRequest: {
          NoResponse: null,
          __typename: 'saveExportDataRequest'
        }
      };
    }
  }
};
```

**Comment by skidding** [comment]
@xavczen Do you have any thoughts on this? Unfortunately I don't have knowledge into Apollo's InMemoryCache API. Thanks!

**Comment by xavczen** [comment]
🤔 it looks good, I don't see what would be wrong.

To figure out what is going on, could you `console.log` the content of the cache before reading it in the `update` function with `JSON.stringify(cache.extract())` and tell us what's inside?

A minimal reproduction on a repo would be awesome 🙏

**Comment by jeznag** [comment]
@xavczen I've set up a minimal reproduction here: https://github.com/COzero/cosmos-apollo-test

I tried logging the cache. It seems to only contain the data for the mutation but not the original query.
```
{"$ROOT_MUTATION.saveExportDataRequest({\"input\":{\"availableOptions\":{},\"exportParameters\":{\"dateRange\":{\"endDate\":\"2019-04-02T00:00:00.000Z\",\"startDate\":\"2018-04-02T00:00:00.000Z\"}},\"selectedMeasurements\":[],\"selectedMeters\":[]}})":{"NoResponse":null,"__typename":"saveExportDataRequest"},"ROOT_MUTATION":{"saveExportDataRequest({\"input\":{\"availableOptions\":{},\"exportParameters\":{\"dateRange\":{\"endDate\":\"2019-04-02T00:00:00.000Z\",\"startDate\":\"2018-04-02T00:00:00.000Z\"}},\"selectedMeasurements\":[],\"selectedMeters\":[]}})":{"type":"id","generated":true,"id":"$ROOT_MUTATION.saveExportDataRequest({\"input\":{\"availableOptions\":{},\"exportParameters\":{\"dateRange\":{\"endDate\":\"2019-04-02T00:00:00.000Z\",\"startDate\":\"2018-04-02T00:00:00.000Z\"}},\"selectedMeasurements\":[],\"selectedMeters\":[]}})","typename":"saveExportDataRequest"}}}
```

**Comment by xavczen** [comment]
> Thanks for the reproduction @jeznag , I got it working thanks to that! 👍 

Part of the problem
---
In the context of this fixture, the cache has never been filled with the result of a `getAvailableOptions` query, you can write manually result in the cache but this query is not watched. 

My assumption is that the caches loose this data written manually when the mutation result is written in the cache ("query watching invalidation"?)

In addition to that, Apollo Client will filter anything that is different from the return value of the mutation:
```js
      resolveWith: apolloData => {
       // ...
       return {
          // this will never be written to the cache,
          // it doesn't fit what should be returned by the mutation
          // availableOptions: fakeData,
          
          // only return what the mutation *is supposed to return* 
          saveExportDataRequest: {
            NoResponse: null,
            __typename: 'saveExportDataRequest',
          },
        };
      },
```

A possible solution
---
We need to get `getAvailableOptions` somewhere to have the mutation updater function to work (ie. use of `cache.readQuery`).

In the fixture, we can wrap `SubmitForm` with a `<Query />` running `getAvailableOptions` and mock the data that would be returned by the API: no need to write the cache when running the mutation.

This gives something like this (tested on your reproduction):

```jsx
import React from 'react';
import { Query } from 'react-apollo';

import SubmitForm from './SubmitForm';
import getAvailableOptions from '../graphql/queries/getAvailableOptions';

class SubmitFormFixture extends React.Component {
  // note: just to make it show up in the fixture tree as "SubmitForm" 😅
  static displayName = 'SubmitForm';

  render() {
    return (
	  {/* query that will be populated with an apollo fixture */}
      <Query query={getAvailableOptions}>
        {() => <SubmitForm />}
      </Query>
    );
  }
}

export default {
  component: SubmitForm,
  apollo: {
    // populate the cache with the data from <Query /> 
    getAvailableOptions: {
      resolveWith: {
        availableOptions: {
          __typename: 'availableOptions',
          availableAggregationLevels: [
            // ...
          ],
          // ...
        },
      },
    },
    // populate the cache when the <Mutation />'s function is called
    saveExportDataRequest: {
      resolveWith: apolloData => {
        return {
          // only return what the mutation *is supposed to return* 
          saveExportDataRequest: {
            NoResponse: null,
            __typename: 'saveExportDataRequest',
          },
        };
      },
    },
  },
};
```

Conclusion
--- 
If a fixture relies on other GraphQL operations result, these results should be mocked too, like in this example: https://github.com/react-cosmos/react-cosmos/blob/master/examples/apollo/components/__fixtures__/Author/mock-with-mutation.js

👆  The mutation depends on the result of a query, the query is mocked so the cache is populated when the mutation reads from it.

In the end, this isn't a bug from Cosmos, I'm closing this issue. 

However, this could be interesting to have a mechanism to populate the cache (start with an initial state for the cache (`cache.restore()` could do that! https://www.apollographql.com/docs/react/features/server-side-rendering.html#store-rehydration 🤔). If you are interested in contributing, feel free to open another issue or even a PR referencing this one, I'll be glad to help!

Cheers

**Comment by skidding** [comment]
Many thanks @xavczen! 👏

**Comment by jeznag** [comment]
Thanks @xavczen! Would it be worth adding an example like this to the docs? I can submit a PR if so. I can't see any examples of tests in there, only fixtures.

**Comment by xavczen** [comment]
Oh yeah please do!
