### ISSUE TITLE
apollo fixture not working - network request still fires

### ISSUE THREAD

**Issue by jeznag** [react-cosmos/react-cosmos#830]
### What's wrong?

See https://github.com/COzero/cosmos-apollo-test/blob/master/src/DataJunction/index.spec.tsx#L20

Apollo has a network error instead of using the fixture
```
console.error node_modules/react-scripts-ts/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/Users/jeremynagel/dev/energylink-project/react-components/cosmos-mutation-test-example/node_modules/react-scripts-ts/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at Request.client.on.err (/Users/jeremynagel/dev/energylink-project/react-components/cosmos-mutation-test-example/node_modules/react-scripts-ts/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
        at emitOne (events.js:101:20)
        at Request.emit (events.js:188:7)
        at Request.onRequestError (/Users/jeremynagel/dev/energylink-project/react-components/cosmos-mutation-test-example/node_modules/request/request.js:877:8)
        at emitOne (events.js:96:13)
        at ClientRequest.emit (events.js:188:7)
        at Socket.socketErrorListener (_http_client.js:310:9)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7) undefined
```

### Steps to reproduce

https://github.com/COzero/cosmos-apollo-test/blob/master/src/DataJunction/index.spec.tsx#L20

### User info

- Server terminal output
- Browser console output
- Cosmos version
- If bug occurred on upgrade: Working Cosmos version
- Cosmos config
- If applicable: webpack version
- If applicable: webpack config

**Comment by xavczen** [comment]
Is this also happening in the cosmos ui for this fixture?

Is this also happening for your other fixtures?
