### ISSUE TITLE
After the Babel 7 upgrade, getting an error when I start cosmos

### ISSUE THREAD

**Issue by dep** [react-cosmos/react-cosmos#919]
When I start cosmos I get the following error:

```
ERROR in /Users/dannypeck/Sites/catalytic-web/node_modules/react-cosmos-flow/fixture.js
Module build failed (from /Users/dannypeck/Sites/catalytic-web/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/dannypeck/Sites/catalytic-web/node_modules/react-cosmos-flow/fixture.js: Unexpected token (3:12)

  1 | // @flow
  2 |
> 3 | import type { Node, ComponentType } from 'react';
    |             ^
  4 | import type { ComponentRef } from './react';
  5 |
  6 | export type FixtureType<P: {}> = {
    at Parser.raise (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:4051:15)
    at Parser.unexpected (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5382:16)
    at Parser.expectContextual (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5350:41)
    at Parser.parseImport (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8823:12)
    at Parser.parseStatementContent (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7586:27)
    at Parser.parseStatement (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7505:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8073:23)
    at Parser.parseBlockBody (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8060:10)
    at Parser.parseTopLevel (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7470:10)
    at Parser.parse (/Users/dannypeck/Sites/catalytic-web/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8915:17)
```

This is my `cosmos.config.js`

```
'use strict';

module.exports = {
  // Set all other paths relative this this one. Important when cosmos.config
  // isn't placed in the project root
  rootPath: '..',

  // Additional entry points that should be present along with any component
  // Sad, but inevitable
  globalImports: ['./config/polyfills'],

  // Set base URL for both webpack assets and static files from publicPath
  // Maps to webpack.output.publicPath
  // https://webpack.js.org/configuration/output/#output-publicpath
  publicUrl: '',

  // Customize proxies file path. Useful if Babel doesn't compile the root dir
  proxiesPath: './config/cosmos.proxies',

  // Disable hot module replacement
  hot: false,

  // Customize webpack config
  webpack: config => {
    // Return customized config
    const { module, resolve } = config;
    const { rules } = module;
    const { extensions } = resolve;

    return {
      ...config,
      module: {
        ...module,
        rules: [
          ...rules,
          // 'svgr' loader converts svg files into React
          // Components. This configuration treats imported svg
          // components as icons, so there height and width will be based
          // on "1em". When you `import` an svg file the default export
          // is a React Component. Additionally, the named export
          // `url` will be the generated data url.
          // For example:
          // ``` js
          // import Star, { url } from './star.svg'
          //
          // const App = () => (
          // <div>
          //   <img src={url} alt="star" />
          //   <Star />
          // </div>
          // )
          // ```
          {
            test: /\.svg$/,
            use: [
              {
                loader: require.resolve('@svgr/webpack'),
                options: { icon: true }
              },
              require.resolve('url-loader')
            ]
          }
        ]
      },
      resolve: {
        ...resolve,
        extensions: [...new Set([...extensions, '.js', '.json'])]
      }
    };
  },

  // Specify where should webpack watch for fixture files (defaults to rootPath)
  watchDirs: ['./src'],

  // Customize output path
  outputPath: './build'
};
```

`package.json`

```
{
  "name": "@foo/bar",
  "version": "0.1.3",
  "main": "index.min.js",
  "license": "SEE LICENSE IN LICENSE",
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "@tippy.js/react": "^1.0.1",
    "change-case": "^3.0.2",
    "classlist-polyfill": "^1.2.0",
    "classnames": "^2.2.5",
    "color": "^3.0.0",
    "css-vendor": "^1.1.0",
    "dom-helpers": "^3.4.0",
    "esm": "^3.0.71",
    "hast-util-sanitize": "^1.2.0",
    "hast-util-to-mdast": "^3.0.0",
    "immutable": "^3.8.2",
    "keycode": "^2.2.0",
    "mdast-util-to-hast": "^3.0.2",
    "path": "^0.12.7",
    "raf": "^3.4.0",
    "ramda": "^0.25.0",
    "react": "^16.6.0",
    "react-color": "^2.14.1",
    "react-datetime": "^2.16.2",
    "react-dom": "^16.6.0",
    "react-dotdotdot": "^1.2.3",
    "react-dropzone": "^4.3.0",
    "react-intl": "^2.4.0",
    "react-jss": "^8.6.1",
    "react-modal": "^3.5.1",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-select": "^2.1.1",
    "react-switch": "^3.0.4",
    "react-textarea-autosize": "^7.1.0",
    "react-toastify": "^4.4.3",
    "recompose": "^0.30.0",
    "remark-parse": "^5.0.0",
    "snyk": "^1.89.0",
    "strip-markdown": "^3.0.2",
    "url-search-params-polyfill": "^4.0.1",
    "whatwg-fetch": "^2.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-external-helpers": "^7.2.0",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/plugin-transform-flow-strip-types": "^7.2.3",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@svgr/rollup": "^4.0.2",
    "@svgr/webpack": "^4.0.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "^8.0.5",
    "babel-plugin-dynamic-import-node": "^2.2.0",
    "catalog": "^3.6.0",
    "enzyme": "^3.6.0",
    "enzyme-adapter-react-16": "^1.6.0",
    "enzyme-to-json": "^3.3.4",
    "eslint": "^4.19.1",
    "flow": "^0.2.3",
    "flow-bin": "^0.78.0",
    "glob": "^7.1.2",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^22.1.4",
    "jest-canvas-mock": "^1.1.0",
    "jest-junit": "^5.0.0",
    "rc-time-picker": "^3.3.1",
    "rc-util": "^4.5.1",
    "react-cosmos": "^4.6.4",
    "react-cosmos-flow": "^4.6.1",
    "react-cosmos-router-proxy": "^4.6.1",
    "react-cosmos-test": "^4.6.4",
    "react-cosmos-wrapper-proxy": "^1.4.0",
    "rimraf": "^2.6.2",
    "rollup": "^0.62.0",
    "rollup-plugin-babel": "^4.3.0",
    "rollup-plugin-flow-entry": "^0.2.0",
    "rollup-plugin-json": "^3.1.0",
    "rollup-plugin-multi-entry": "^2.1.0",
    "rollup-plugin-node-resolve": "^4.0.0",
    "rollup-plugin-postcss": "^1.6.3",
    "sinon": "^4.2.1",
    "url-loader": "1.1.2"
  },
  "scripts": {
    "build": "yarn build:cosmos && yarn build:catalog && yarn build:source",
    "build:catalog": "cd src && catalog build --public-url /ui/catalog/",
    "build:cosmos": "yarn cosmos:export",
    "build:source": "NODE_ENV=production yarn rollup -c",
    "catalog": "cd src && catalog start",
    "clean": "rimraf build",
    "cosmos": "cosmos --config config/cosmos.config.js",
    "cosmos:export": "cosmos-export --config config/cosmos.config.js",
    "lint": "yarn eslint .",
    "lint-fix": "yarn eslint --fix -f codeframe .",
    "lint-staged": "yarn eslint --fix -f codeframe",
    "start": "yarn cosmos",
    "test": "TZ=UTC jest --env=jsdom"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "forceExit": true,
    "setupFiles": [
      "<rootDir>/config/polyfills.js",
      "<rootDir>/config/enzyme.js",
      "jest-canvas-mock"
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ],
    "testMatch": [
      "<rootDir>/{config,src}/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/{config,src}/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/../../node_modules/babel-jest",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "/node_modules/(?!react-cosmos-flow)"
    ],
    "moduleNameMapper": {
      "^.+\\.css$": "identity-obj-proxy",
      "^.+\\.svg$": "<rootDir>/config/jest/svgMock.js",
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "mjs",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ],
    "reporters": [
      "default",
      "jest-junit"
    ]
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/react",
      "@babel/preset-flow"
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties",
      "babel-plugin-dynamic-import-node"
    ]
  }
}
```

and finally my `rollup.config`

```
import flowEntry from 'rollup-plugin-flow-entry';
import multiEntry from 'rollup-plugin-multi-entry';
import json from 'rollup-plugin-json';
import resolve from 'rollup-plugin-node-resolve';
import postcss from 'rollup-plugin-postcss';
import svgr from '@svgr/rollup';
import babel from 'rollup-plugin-babel';

export default {
  input: {
    include: [
      'config/polyfills.js',
      'src/**/!(*.fixture|*.test|*intl-enzyme-test-helper).js'
    ],
    exclude: ['src/catalog/**/*']
  },
  output: {
    file: 'index.min.js',
    sourcemap: true,
    format: 'cjs'
  },
  external: [
    '@catalytic/catalytic-icons',
    '@tippy.js/react',
    'classnames',
    'color',
    'css-vendor',
    'dom-helpers/activeElement',
    'hast-util-sanitize',
    'hast-util-to-mdast',
    'immutable',
    'keycode',
    'mdast-util-to-hast',
    'ramda/src/compose',
    'ramda/src/path',
    'rc-time-picker',
    'react',
    'react-color',
    'react-datetime',
    'react-dotdotdot',
    'react-dropzone',
    'react-intl',
    'react-jss',
    'react-modal',
    'react-router-dom',
    'react-select',
    'react-switch',
    'react-textarea-autosize',
    'react-toastify',
    'recompose',
    'remark-parse',
    'strip-markdown'
  ],
  plugins: [
    flowEntry(),
    multiEntry(),
    json(),
    resolve({ extensions: ['.js', '.json'] }),
    postcss({ extensions: ['.css'] }),
    svgr({ icon: true }),
    babel({
      exclude: 'node_modules/**'
    })
  ]
};
```

Thanks in advance for any help

**Comment by skidding** [comment]
Hi @dep,

Do you import `react-cosmos-flow` yourself in any file? It's hard to see from the stack trace because it's all Babel parse modules.

**Comment by dep** [comment]
Hi @skidding thanks for the reply. As far as imports, I do quite a lot of this:

```
import { createFixture } from 'react-cosmos-flow/fixture';
```

**Comment by dep** [comment]
Oddly enough moving my `babel` config out to a proper `babel.config.js` fixed this for me.

```
module.exports = function(api) {
  api.cache(true);
  const presets = [
    [
      '@babel/preset-env',
      {
        modules: 'auto',
        targets: {
          browsers: ['defaults']
        },
        useBuiltIns: 'entry'
      }
    ],
    '@babel/react',
    '@babel/preset-flow'
  ];
  const plugins = [
    '@babel/plugin-proposal-class-properties',
    'babel-plugin-dynamic-import-node'
  ];

  return {
    presets,
    plugins
  };
};
```

**Comment by skidding** [comment]
Good news,

Can you try using `import { createFixture } from 'react-cosmos'` instead?

From what I recall `react-cosmos-flow` was deprecated in favor of this simpler approach.
