### ISSUE TITLE
Cosmos Next Multi Fixture not working as described

### ISSUE THREAD

**Issue by MichielHegemans** [react-cosmos/react-cosmos#940]
### What's wrong?

The description of cosmos-next says we can export multifixture when the export is the default export of a module. However when I attempt this I get the following error: `Objects are not valid as a React child`

### Steps to reproduce

Fixture:
```jsx
import React from 'react';

export default {
    one: <div />,
    two: <div />,
}
```

cosmos.next.config.js
```js
module.exports = {
    webpackConfigPath: 'webpack.cosmos.js',
    next: true,
    port: 9999,
};
```

webpack.cosmos.js
```js
module.exports = {
    mode: 'development',
    devtool: 'inline-source-map',
    resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.scss'],
    },
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ["@babel/env", "@babel/react"],
                }
            },
        ],
    },
};
```

### Screenshots

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/27996963/54812610-c7eeec80-4c8b-11e9-8520-69106e359003.png">

### User info

- Server terminal output
- Browser console output
- Cosmos version: 4.7.0
- If applicable: webpack version: 4.29.6

log:
```
client.js?reload=true&overlay=false:92 [HMR] connected
react-dom.development.js:55 Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {one, two}). If you meant to render a collection of children, use an array instead.
    in FixtureCaptureInner (created by Context.Consumer)
    in FixtureCapture (created by FixtureProvider)
    in ErrorCatch (created by FixtureProvider)
    in FixtureProvider (created by FixtureConnect)
    in FixtureConnect (created by PostMessage)
    in PostMessage
    at invariant (http://localhost:9999/main.js:33930:15)
    at throwOnInvalidObjectType (http://localhost:9999/main.js:45662:5)
    at reconcileChildFibers (http://localhost:9999/main.js:46436:7)
    at reconcileChildren (http://localhost:9999/main.js:48231:28)
    at finishClassComponent (http://localhost:9999/main.js:48587:5)
    at updateClassComponent (http://localhost:9999/main.js:48525:24)
    at beginWork (http://localhost:9999/main.js:49473:16)
    at performUnitOfWork (http://localhost:9999/main.js:53141:12)
    at workLoop (http://localhost:9999/main.js:53181:24)
    at HTMLUnknownElement.callCallback (http://localhost:9999/main.js:34024:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9999/main.js:34074:16)
    at invokeGuardedCallback (http://localhost:9999/main.js:34131:31)
    at replayUnitOfWork (http://localhost:9999/main.js:52407:5)
    at renderRoot (http://localhost:9999/main.js:53297:13)
    at performWorkOnRoot (http://localhost:9999/main.js:54171:7)
    at performWork (http://localhost:9999/main.js:54083:7)
    at performSyncWork (http://localhost:9999/main.js:54057:3)
    at requestWork (http://localhost:9999/main.js:53926:5)
    at scheduleWork (http://localhost:9999/main.js:53740:5)
    at Object.enqueueSetState (http://localhost:9999/main.js:45019:5)
    at FixtureConnect../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:9999/main.js:56569:16)
    at FixtureConnect.handleSelectFixtureRequest (http://localhost:9999/main.js:32634:12)
    at PostMessage.onMessage (http://localhost:9999/main.js:32505:24)
    at http://localhost:9999/main.js:32264:15
invariant @ react-dom.development.js:55
throwOnInvalidObjectType @ react-dom.development.js:11787
reconcileChildFibers @ react-dom.development.js:12561
reconcileChildren @ react-dom.development.js:14356
finishClassComponent @ react-dom.development.js:14712
updateClassComponent @ react-dom.development.js:14650
beginWork @ react-dom.development.js:15598
performUnitOfWork @ react-dom.development.js:19266
workLoop @ react-dom.development.js:19306
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18532
renderRoot @ react-dom.development.js:19422
performWorkOnRoot @ react-dom.development.js:20296
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
enqueueSetState @ react-dom.development.js:11144
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
handleSelectFixtureRequest @ index.js:220
(anonymous) @ index.js:91
(anonymous) @ PostMessage.js:47
postMessage (async)
onRendererRequest @ _playground.js:86
(anonymous) @ _playground.js:54
(anonymous) @ _playground.js:54
emitEvent @ _playground.js:54
p @ _playground.js:86
s @ _playground.js:86
(anonymous) @ _playground.js:86
(anonymous) @ _playground.js:86
setState @ _playground.js:54
g @ _playground.js:86
b @ _playground.js:86
callMethod @ _playground.js:54
(anonymous) @ _playground.js:86
postMessage (async)
(anonymous) @ PostMessage.js:59
postReadyState @ index.js:255
componentDidMount @ index.js:149
commitLifeCycles @ react-dom.development.js:17288
commitAllLifeCycles @ react-dom.development.js:18690
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18902
(anonymous) @ react-dom.development.js:20372
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20371
performWorkOnRoot @ react-dom.development.js:20300
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
mount @ mount.js:23
mount @ index.js:13
./node_modules/react-cosmos/dist/client/next/index.js @ index.js:21
__webpack_require__ @ bootstrap:723
fn @ bootstrap:100
0 @ main.js:62893
__webpack_require__ @ bootstrap:723
(anonymous) @ bootstrap:790
(anonymous) @ bootstrap:790
index.js:1 The above error occurred in the <FixtureCaptureInner> component:
    in FixtureCaptureInner (created by Context.Consumer)
    in FixtureCapture (created by FixtureProvider)
    in ErrorCatch (created by FixtureProvider)
    in FixtureProvider (created by FixtureConnect)
    in FixtureConnect (created by PostMessage)
    in PostMessage

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorCatch.
function.console.(anonymous function) @ index.js:1
logCapturedError @ react-dom.development.js:17071
logError @ react-dom.development.js:17107
callback @ react-dom.development.js:18048
callCallback @ react-dom.development.js:16387
commitUpdateEffects @ react-dom.development.js:16426
commitUpdateQueue @ react-dom.development.js:16417
commitLifeCycles @ react-dom.development.js:17318
commitAllLifeCycles @ react-dom.development.js:18690
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18902
(anonymous) @ react-dom.development.js:20372
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20371
performWorkOnRoot @ react-dom.development.js:20300
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
enqueueSetState @ react-dom.development.js:11144
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
handleSelectFixtureRequest @ index.js:220
(anonymous) @ index.js:91
(anonymous) @ PostMessage.js:47
postMessage (async)
onRendererRequest @ _playground.js:86
(anonymous) @ _playground.js:54
(anonymous) @ _playground.js:54
emitEvent @ _playground.js:54
p @ _playground.js:86
s @ _playground.js:86
(anonymous) @ _playground.js:86
(anonymous) @ _playground.js:86
setState @ _playground.js:54
g @ _playground.js:86
b @ _playground.js:86
callMethod @ _playground.js:54
(anonymous) @ _playground.js:86
postMessage (async)
(anonymous) @ PostMessage.js:59
postReadyState @ index.js:255
componentDidMount @ index.js:149
commitLifeCycles @ react-dom.development.js:17288
commitAllLifeCycles @ react-dom.development.js:18690
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18902
(anonymous) @ react-dom.development.js:20372
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20371
performWorkOnRoot @ react-dom.development.js:20300
performWork @ react-dom.development.js:20208
performSyncWork @ react-dom.development.js:20182
requestWork @ react-dom.development.js:20051
scheduleWork @ react-dom.development.js:19865
scheduleRootUpdate @ react-dom.development.js:20526
updateContainerAtExpirationTime @ react-dom.development.js:20554
updateContainer @ react-dom.development.js:20611
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20907
(anonymous) @ react-dom.development.js:21044
unbatchedUpdates @ react-dom.development.js:20413
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21040
render @ react-dom.development.js:21109
mount @ mount.js:23
mount @ index.js:13
./node_modules/react-cosmos/dist/client/next/index.js @ index.js:21
__webpack_require__ @ bootstrap:723
fn @ bootstrap:100
0 @ main.js:62893
__webpack_require__ @ bootstrap:723
(anonymous) @ bootstrap:790
(anonymous) @ bootstrap:790
```

**Comment by skidding** [comment]
Sorry for the confusion. The multi fixtures feature was pre-released. Install `react-cosmos@next` to enable it. Hoping to make it official next week.

**Comment by MichielHegemans** [comment]
Oh sorry. Thanks for responding!
